# Generated by Django 5.1.3 on 2025-03-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
