# Generated by Django 5.1.3 on 2025-03-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
