# Generated by Django 5.1.3 on 2025-03-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piwallet',
            options={'ordering': ['-connected_at'], 'verbose_name': 'Pi Wallet', 'verbose_name_plural': 'Pi Wallets'},
        ),
    ]
