# Generated by Django 5.1.3 on 2025-03-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_piwallet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piwallet',
            options={},
        ),
        migrations.RemoveField(
            model_name='piwallet',
            name='wallet_address',
        ),
    ]
