# Generated by Django 5.1.3 on 2025-03-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
