# Generated by Django 4.2 on 2025-03-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
